/**
 * 콘텐츠 split 코드젠 — PRO 유료 본문을 클라이언트 번들에서 분리한다(H1).
 *
 * 단일 소스(authored TS, 예: content/projects.data.ts)를 빌드 타임에 평가해:
 *   - 클라이언트용: 메타데이터 + 무료 본문 + PRO 의 "티저"(제목/개요)만 남긴
 *     stripped 모듈 → src/content/generated/*.generated.ts
 *   - 서버용: PRO 의 실제 본문(정답·스니펫·스타터 코드) → api/_generated/*.generated.ts
 *     (Vercel Function 이 인증·entitlement 확인 후 제공)
 *
 * 실행: `npx tsx scripts/split-content.ts` (build 스크립트가 vite 빌드 전에 호출)
 *
 * 생성 파일은 레포에 커밋한다(개발 서버·tsc 가 코드젠 없이도 동작하도록).
 *
 * 현재 도메인: projects. (workshops/lessons/courses 는 동일 패턴으로 확장)
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { PROJECTS, type Project, type ProjectStep } from "../src/content/projects.data";
import { WORKSHOP_LESSONS } from "../src/content/ai-engineering/workshops/data";
import { isProjectPro, isWorkshopPro } from "../src/content/tier";
import type { Lesson } from "../src/types/lesson";

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = resolve(__dirname, "..");

const GENERATED_NOTICE =
  "// ⚠️ AUTO-GENERATED by scripts/split-content.ts — 직접 수정하지 마세요.\n" +
  "// 원본: src/content/*.data.ts. 변경하려면 원본을 고치고 `npm run codegen` 실행.\n\n";

function writeGenerated(relPath: string, contents: string): void {
  const abs = resolve(APP_ROOT, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, GENERATED_NOTICE + contents, "utf-8");
  console.log(`[split-content] wrote ${relPath}`);
}

// ─────────────────────────────────────────────────────────
// projects 도메인
// ─────────────────────────────────────────────────────────

/** PRO 프로젝트에서 클라이언트에 남길 step (제목/마커만 — 티저). */
function stripStep(step: string | ProjectStep): string | ProjectStep {
  if (typeof step === "string") return step; // 문자열 step 은 제목뿐이라 그대로
  const { title, stepMarker } = step;
  return stepMarker !== undefined ? { title, stepMarker } : { title };
}

interface ProjectBody {
  steps: (string | ProjectStep)[];
  starterFiles: Project["starterFiles"];
}

const clientProjects: Project[] = [];
const proBodies: Record<string, ProjectBody> = {};

for (const project of PROJECTS) {
  if (isProjectPro(project.id)) {
    // PRO: 실제 본문(정답 포함 step + 스타터 코드)을 서버로 분리.
    proBodies[project.id] = {
      steps: project.steps,
      starterFiles: project.starterFiles,
    };
    // 클라이언트엔 메타 + 개요(description) + step 제목만.
    clientProjects.push({
      ...project,
      steps: project.steps.map(stripStep),
      starterFiles: {},
    });
  } else {
    // 무료: 전체 그대로 클라이언트에 유지.
    clientProjects.push(project);
  }
}

writeGenerated(
  "src/content/generated/projects.generated.ts",
  `import type { Project } from "../projects.data";\n\n` +
    `export const CLIENT_PROJECTS: Project[] = ${JSON.stringify(clientProjects, null, 2)};\n`,
);

writeGenerated(
  "api/_generated/proProjects.generated.ts",
  `/** PRO 프로젝트 본문 — 서버 전용. Vercel Function 이 인증 후 제공. */\n` +
    `export interface ProjectBody {\n` +
    `  steps: unknown[];\n` +
    `  starterFiles: Record<string, { name: string; content: string; language: string }>;\n` +
    `}\n\n` +
    `export const PRO_PROJECT_BODIES: Record<string, ProjectBody> = ${JSON.stringify(
      proBodies,
      null,
      2,
    )};\n`,
);

console.log(
  `[split-content] projects: ${clientProjects.length} total, ${Object.keys(proBodies).length} PRO 본문 분리`,
);

// ─────────────────────────────────────────────────────────
// workshops 도메인 (Lesson.cells 기반)
// ─────────────────────────────────────────────────────────

type Cell = Lesson["cells"][number];

/** 마크다운 셀들에서 ==용어== 추출 (WorkshopDetailPage 와 동일 규칙). */
function glossaryFromCells(cells: Cell[]): string[] {
  const terms: string[] = [];
  for (const c of cells) {
    if (c.type !== "markdown") continue;
    for (const m of c.source.matchAll(/==([^=]+)==/g)) {
      const t = m[1].trim();
      if (!terms.includes(t)) terms.push(t);
    }
  }
  return terms;
}

const clientWorkshops: Lesson[] = [];
const proWorkshopBodies: Record<string, Cell[]> = {};
const workshopTeaser: Record<string, { llmCellCount: number; glossaryTerms: string[] }> = {};

for (const w of WORKSHOP_LESSONS) {
  if (isWorkshopPro(w.order)) {
    // PRO: 실제 본문(전체 cells)을 서버로 분리. 클라엔 첫 마크다운 셀(인트로 티저)만.
    proWorkshopBodies[w.id] = w.cells;
    workshopTeaser[w.id] = {
      llmCellCount: w.cells.filter((c) => c.type === "llm-code").length,
      glossaryTerms: glossaryFromCells(w.cells),
    };
    const firstMd = w.cells.find((c) => c.type === "markdown");
    clientWorkshops.push({ ...w, cells: firstMd ? [firstMd] : [] });
  } else {
    // 무료 워크샵(W00~W06): 전체 그대로 클라이언트에 유지.
    clientWorkshops.push(w);
  }
}

writeGenerated(
  "src/content/ai-engineering/workshops/generated.ts",
  `import type { Lesson } from "../../../types/lesson";\n\n` +
    `export interface WorkshopTeaserMeta {\n  llmCellCount: number;\n  glossaryTerms: string[];\n}\n\n` +
    `export const CLIENT_WORKSHOP_LESSONS: Lesson[] = ${JSON.stringify(clientWorkshops, null, 2)};\n\n` +
    `export const WORKSHOP_TEASER_META: Record<string, WorkshopTeaserMeta> = ${JSON.stringify(
      workshopTeaser,
      null,
      2,
    )};\n`,
);

writeGenerated(
  "api/_generated/proWorkshops.generated.ts",
  `/** PRO 워크샵 본문(cells) — 서버 전용. Vercel Function 이 인증 후 제공. */\n` +
    `export const PRO_WORKSHOP_BODIES: Record<string, unknown[]> = ${JSON.stringify(
      proWorkshopBodies,
      null,
      2,
    )};\n`,
);

console.log(
  `[split-content] workshops: ${clientWorkshops.length} total, ${Object.keys(proWorkshopBodies).length} PRO 본문 분리`,
);
